import { CreditNotFoundError, signCreditOutboxEvent } from '@resvary/sdk/credits';
import { ArcCreditFunding } from '@resvary/sdk/funding/arc';
import { createReceipt } from '@resvary/sdk/receipts';
import { createHash } from 'node:crypto';
import { getDemoCredits } from './store';

export const dynamic = 'force-dynamic';

const customerId = 'customer_demo';
const fundingRecipient = '0x1111111111111111111111111111111111111111' as const;
const fundingPayer = '0x2222222222222222222222222222222222222222' as const;

export async function GET() {
  return Response.json(await getState());
}

export async function POST(request: Request) {
  try {
    const body = (await request.json()) as {
      action?: string;
      idempotencyKey?: string;
      live?: boolean;
    };
    const { ledger, price } = await getDemoCredits();
    const idempotencyKey = body.idempotencyKey ?? crypto.randomUUID();

    if (body.action === 'grant') {
      await ledger.grantCredits({
        customerId,
        amount: '5',
        idempotencyKey: `grant:${idempotencyKey}`,
      });
    } else if (body.action === 'run') {
      await ledger.runMetered(
        {
          customerId,
          priceId: price.id,
          estimatedUsage: body.live
            ? { input_tokens: '4000', output_tokens: '1000' }
            : { input_tokens: '2000', output_tokens: '1000' },
          idempotencyKey: `run:${idempotencyKey}`,
          metadata: { mode: body.live ? 'live' : 'simulated' },
        },
        async () => (body.live ? callLiveProvider() : simulateProvider(idempotencyKey)),
      );
    } else if (body.action === 'fail') {
      try {
        await ledger.runMetered(
          {
            customerId,
            priceId: price.id,
            estimatedUsage: { input_tokens: '1000', output_tokens: '1000' },
            idempotencyKey: `fail:${idempotencyKey}`,
            metadata: { mode: 'simulated_failure' },
          },
          async () => {
            throw new Error('Simulated provider timeout');
          },
        );
      } catch (error) {
        if (!(error instanceof Error) || error.message !== 'Simulated provider timeout')
          throw error;
      }
    } else if (body.action === 'arc') {
      const funding = new ArcCreditFunding({ ledger, payTo: fundingRecipient });
      const fundingRequest = await funding.createFundingRequest({
        customerId,
        amount: '2',
        idempotencyKey: `arc-intent:${idempotencyKey}`,
        metadata: { mode: 'simulated_arc_testnet' },
      });
      const txHash =
        `0x${createHash('sha256').update(idempotencyKey).digest('hex')}` as `0x${string}`;
      const receipt = createReceipt(fundingRequest.invoice, {
        from: fundingPayer,
        to: fundingRecipient,
        amount: '2',
        memo: fundingRequest.invoice.memo,
        txHash,
      });
      await funding.confirmPayment({
        fundingIntentId: fundingRequest.fundingIntent.id,
        receipt,
        idempotencyKey: `arc-confirm:${idempotencyKey}`,
      });
    } else {
      return Response.json({ error: 'Unknown action' }, { status: 400 });
    }

    return Response.json(await getState());
  } catch (error) {
    return Response.json(
      {
        error: error instanceof Error ? error.message : 'Credit operation failed',
        state: await getState(),
      },
      { status: 409 },
    );
  }
}

async function getState() {
  const { ledger, price } = await getDemoCredits();
  let balance = null;
  try {
    balance = await ledger.getBalance(customerId);
  } catch (error) {
    if (!(error instanceof CreditNotFoundError)) throw error;
  }
  const outboxEvents = await ledger.listOutboxEvents();
  const latestEvent = outboxEvents.at(-1);
  return {
    customerId,
    balance,
    price,
    reservations: await ledger.store.listReservations({ projectId: ledger.projectId, customerId }),
    receipts: balance ? await ledger.listUsageReceipts(customerId) : [],
    ledgerEntries: balance ? await ledger.listLedgerEntries(customerId) : [],
    outboxEvents,
    latestSignature: latestEvent
      ? signCreditOutboxEvent(
          latestEvent,
          process.env.RESVARY_WEBHOOK_SECRET ?? 'resvary-demo-secret',
        ).header
      : null,
    liveProviderConfigured: Boolean(
      process.env.RESVARY_AI_API_KEY && process.env.RESVARY_AI_MODEL,
    ),
    persistence: process.env.RESVARY_CREDITS_DB_PATH ?? '.resvary/demo.sqlite',
    fundingIntents: await ledger.listFundingIntents(),
    fundingTransactions: await ledger.listFundingTransactions(),
  };
}

async function simulateProvider(idempotencyKey: string) {
  return {
    value: { text: 'A simulated answer generated by the Resvary demo.' },
    actualUsage: { input_tokens: '1260', output_tokens: '310' },
    usageEventId: `simulated:${idempotencyKey}`,
  };
}

async function callLiveProvider() {
  const apiKey = process.env.RESVARY_AI_API_KEY;
  const model = process.env.RESVARY_AI_MODEL;
  const baseUrl = (process.env.RESVARY_AI_BASE_URL ?? 'https://api.openai.com/v1').replace(
    /\/$/,
    '',
  );
  if (!apiKey || !model) throw new Error('Live provider is not configured');

  const response = await fetch(`${baseUrl}/chat/completions`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', authorization: `Bearer ${apiKey}` },
    body: JSON.stringify({
      model,
      messages: [{ role: 'user', content: 'Explain prepaid AI credits in one sentence.' }],
    }),
  });
  if (!response.ok) throw new Error(`AI provider returned ${response.status}`);
  const data = (await response.json()) as {
    id?: string;
    choices?: Array<{ message?: { content?: string } }>;
    usage?: { prompt_tokens?: number; completion_tokens?: number };
  };
  if (!data.id || !data.usage) throw new Error('AI provider response did not include usage');
  return {
    value: { text: data.choices?.[0]?.message?.content ?? '' },
    actualUsage: {
      input_tokens: String(data.usage.prompt_tokens ?? 0),
      output_tokens: String(data.usage.completion_tokens ?? 0),
    },
    usageEventId: data.id,
  };
}
