version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      production-dependencies:
        patterns:
          - '*'
        dependency-type: production
      development-dependencies:
        patterns:
          - '*'
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3

  - package-ecosystem: docker
    directory: /apps/agent-demo
    schedule:
      interval: weekly
    open-pull-requests-limit: 2

  - package-ecosystem: docker
    directory: /apps/console
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
